executable = "aftereffects_2021"
schema = "avalon-core:application-1.0"
application_dir = "aftereffects"
label = "Adobe After Effects"
label_variant = "2021"
icon = "app_icons/aftereffects.png"
ftrack_label = "After Effects"
ftrack_icon = '{}/app_icons/aftereffects.png'
launch_hook = "pype/hooks/aftereffects/prelaunch.py/AfterEffectsPrelaunch"