application_dir = "blender"
executable = "blender_2.80"
schema = "avalon-core:application-1.0"
label = "Blender"
label_variant = "2.80"
ftrack_label = "Blender"
icon = "app_icons/blender.png"
ftrack_icon = "{}/app_icons/blender.png"
