application_dir = "harmony"
label = "Harmony"
label_variant = "17"
ftrack_label = "Harmony"
schema = "avalon-core:application-1.0"
executable = "harmony_17"
description = ""
icon = "app_icons/harmony.png"
ftrack_icon = '{}/app_icons/harmony.png'
