executable = "nuke12.0"
schema = "avalon-core:application-1.0"
application_dir = "nuke"
label = "Nuke"
label_variant = "12.0"
ftrack_label = "Nuke"
icon = "app_icons/nuke.png"
ftrack_icon = '{}/app_icons/nuke.png'
