executable = "nuke11.3"
schema = "avalon-core:application-1.0"
application_dir = "nuke"
label = "Nuke"
label_variant = "11.3"
ftrack_label = "Nuke"
icon = "app_icons/nuke.png"
ftrack_icon = '{}/app_icons/nuke.png'
