executable = "nukex11.3"
schema = "avalon-core:application-1.0"
application_dir = "nuke"
label = "NukeX"
label_variant = "11.3"
ftrack_label = "NukeX"
icon = "app_icons/nuke.png"
ftrack_icon = '{}/app_icons/nukex.png'
