executable = "photoshop_2021"
schema = "avalon-core:application-1.0"
application_dir = "photoshop"
label = "Adobe Photoshop"
label_variant = "2021"
icon = "app_icons/photoshop.png"
ftrack_label = "Photoshop"
ftrack_icon = '{}/app_icons/photoshop.png'
launch_hook = "pype/hooks/photoshop/prelaunch.py/PhotoshopPrelaunch"
