executable = "tvpaint_11.0"
schema = "avalon-core:application-1.0"
application_dir = "tvpaint"
label = "TVPaint Animation"
label_variant = "11.0"
ftrack_label = "TVPaint Animation"
icon = "app_icons/tvpaint.png"
ftrack_icon = '{}/app_icons/tvpaint.png'
launch_hook = "pype/hooks/tvpaint/prelaunch.py/TvpaintPrelaunchHook"
