executable = "tvpaint11"
schema = "avalon-core:application-1.0"
application_dir = "tvpaint"
label = "TVPaint Animation 11"
icon = "app_icons/tvpaint.png"
launch_hook = "pype/hooks/tvpaint/prelaunch.py/TvpaintPrelaunchHook"

ftrack_label = "TVPaint Animation"
ftrack_icon = '{}/app_icons/tvpaint.png'
